In [22]:
# Import necessary packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.model_selection import GridSearchCV



# Load dataset from CSV file
data = pd.read_csv('labeled_line_data.csv')  # Replace 'your_file.csv' with your actual filename

data.head()  


slope     length      mid_x      mid_y  label
0 -7.706164  54.947870  23.161904  -5.842437      2
1 -0.039858  13.700817 -20.682028  45.790013      0
2 -0.535722  82.397350 -26.919301  30.696419      0
3  3.201565  63.719220 -26.521091 -19.172285      1
4 -1.809498  33.675274 -17.314719  13.617172      2

In [23]:
X=data.drop(columns=['label'])
y=data['label']
y.head()

0    2
1    0
2    0
3    1
4    2
Name: label, dtype: int64

In [24]:
scalar=StandardScaler()
x_scaled=scalar.fit_transform(X)
X_scaled=pd.DataFrame(x_scaled,columns=X.columns)
X_scaled.head()  

slope    length     mid_x     mid_y
0 -1.535315 -0.016257  0.792545 -0.191302
1 -0.005838 -1.604957 -0.725075  1.604195
2 -0.104766  1.041006 -0.940973  1.079322
3  0.640847  0.321586 -0.927190 -0.654842
4 -0.358893 -0.835607 -0.608519  0.485398

In [25]:
X_train,X_valid,y_train,y_valid=train_test_split(X_scaled,y,test_size=0.2,random_state=42)
y_train.head()
print(y.value_counts())

2    3000
0    3000
1    3000
Name: label, dtype: int64


In [28]:


param_grid = {
    'C': [0.1, 1, 10, 100],         
    'gamma': ['scale', 0.01, 0.001, 0.0001],  
    'kernel': ['rbf']
}


grid_search = GridSearchCV(
    estimator=SVC(),
    param_grid=param_grid,
    cv=5,               
    scoring='accuracy', 
    verbose=2,
    n_jobs=-1            
)


grid_search.fit(X_train, y_train)
y_pred = grid_search.predict(X_valid)


Fitting 5 folds for each of 16 candidates, totalling 80 fits


In [29]:
print("Accuracy:", accuracy_score(y_valid, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_valid, y_pred))
print("Classification Report:\n", classification_report(y_valid, y_pred))

Accuracy: 0.9922222222222222
Confusion Matrix:
 [[611   0   0]
 [  9 608   0]
 [  5   0 567]]
Classification Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99       611
           1       1.00      0.99      0.99       617
           2       1.00      0.99      1.00       572

    accuracy                           0.99      1800
   macro avg       0.99      0.99      0.99      1800
weighted avg       0.99      0.99      0.99      1800

